In [26]:
import duckdb

In [27]:
df = duckdb.read_csv("author_history_with_term_2025-03-21.csv")

In [28]:
df.write_parquet("author_history_2025_03_21.parquet")
df.write_csv("author_history_2025_03_21.csv")

In [29]:
author_df = duckdb.sql("SELECT DISTINCT author_id, author, birth_year, sex, ethnicity FROM df")

In [30]:
author_df.write_parquet("author_2025_03_21.parquet")
author_df.write_csv("author_2025_03_21.csv")

In [31]:
author_df

┌───────────┬─────────────────────────────────┬────────────┬─────────┬────────────┐
│ author_id │             author              │ birth_year │   sex   │ ethnicity  │
│   int64   │             varchar             │   int64    │ varchar │  varchar   │
├───────────┼─────────────────────────────────┼────────────┼─────────┼────────────┤
│      1981 │ CHOR CHEE HEUNG                 │       1955 │ male    │ chinese    │
│      2190 │ ONG KA TING                     │       1957 │ male    │ chinese    │
│      2874 │ CHONG CHIENG JEN                │       1971 │ male    │ chinese    │
│      3305 │ ABDUL AZEEZ BIN ABDUL RAHIM     │       1967 │ male    │ bumiputera │
│      3315 │ WAN ABD. RAHIM BIN WAN ABDULLAH │       1952 │ male    │ bumiputera │
│      3324 │ ANNUAR BIN HAJI MUSA            │       1956 │ male    │ bumiputera │
│      3371 │ HAMZAH BIN ZAINUDIN             │       1957 │ male    │ bumiputera │
│      3388 │ MOHD NIZAR BIN HAJI ZAKARIA     │       1969 │ male    │ bumiputera │
│      3470 │ LILAH BIN YASIN                 │       1958 │ male    │ bumiputera │
│      3473 │ JOHN A/L FERNANDEZ              │       1942 │ male    │ indian     │
│        ·  │        ·                        │         ·  │  ·      │   ·        │
│        ·  │        ·                        │         ·  │  ·      │   ·        │
│        ·  │        ·                        │         ·  │  ·      │   ·        │
│     20692 │ AZHAR BIN AHMAD                 │       NULL │ male    │ bumiputera │
│     20865 │ KHAIRIAH BINTI MOHAMED          │       NULL │ female  │ bumiputera │
│     20975 │ MOHD APANDI BIN MOHAMAD         │       NULL │ male    │ bumiputera │
│     21013 │ MUHAMAD BIN MUSTAFA             │       NULL │ male    │ bumiputera │
│     21026 │ MUSODDAK BIN AHMAD              │       NULL │ male    │ bumiputera │
│     21038 │ NALLAKARUPPAN A/L SOLAIMALAI    │       NULL │ male    │ indian     │
│     21129 │ ROSLIN BINTI ABDUL RAHMAN       │       NULL │ female  │ bumiputera │
│     21188 │ SUBRAMANIAM A/L VERUTHASALAM    │       NULL │ male    │ indian     │
│     21220 │ TEO ENG TEE @ TEO KOK CHEE      │       NULL │ male    │ chinese    │
│     21272 │ ZAHARI BIN SARIP                │       NULL │ male    │ bumiputera │
├───────────┴─────────────────────────────────┴────────────┴─────────┴────────────┤
│ 701 rows (20 shown)                                                   5 columns │
└─────────────────────────────────────────────────────────────────────────────────┘

In [32]:
df

┌───────────┬───────┬────────────────────────────────────┬────────────┬─────────┬────────────┬───────────┬──────────────┬──────────────────┬─────────────┬────────────┬─────────────────────────────┬────────────┬────────────┐
│ author_id │  vol  │               author               │ birth_year │   sex   │ ethnicity  │   party   │    negeri    │       area       │ kod_kawasan │ exec_posts │        service_posts        │ start_date │  end_date  │
│   int64   │ int64 │              varchar               │   int64    │ varchar │  varchar   │  varchar  │   varchar    │     varchar      │   varchar   │  varchar   │           varchar           │    date    │    date    │
├───────────┼───────┼────────────────────────────────────┼────────────┼─────────┼────────────┼───────────┼──────────────┼──────────────────┼─────────────┼────────────┼─────────────────────────────┼────────────┼────────────┤
│       375 │    14 │ MAHATHIR BIN MOHAMAD               │       1926 │ male    │ bumiputera │ BERSATU   │ Kedah        │ LANGKAWI         │ P004        │ NULL       │ NULL                        │ 2018-05-09 │ 2020-05-28 │
│       375 │    14 │ MAHATHIR BIN MOHAMAD               │       1926 │ male    │ bumiputera │ BEBAS     │ Kedah        │ LANGKAWI         │ P004        │ NULL       │ NULL                        │ 2020-05-28 │ 2020-08-12 │
│       375 │    14 │ MAHATHIR BIN MOHAMAD               │       1926 │ male    │ bumiputera │ PEJUANG   │ Kedah        │ LANGKAWI         │ P004        │ NULL       │ NULL                        │ 2020-08-12 │ 2022-10-10 │
│       698 │    12 │ LIM KIT SIANG                      │       1941 │ male    │ chinese    │ DAP       │ Perak        │ Ipoh Timur       │ P064        │ NULL       │ NULL                        │ 2008-03-08 │ 2013-04-03 │
│       698 │    13 │ LIM KIT SIANG                      │       1941 │ male    │ chinese    │ DAP       │ Johor        │ Gelang Patah     │ P162        │ NULL       │ NULL                        │ 2013-05-05 │ 2018-04-07 │
│       698 │    14 │ LIM KIT SIANG                      │       1941 │ male    │ chinese    │ PH - DAP  │ Johor        │ ISKANDAR PUTERI  │ P162        │ NULL       │ NULL                        │ 2018-05-09 │ 2022-10-10 │
│       848 │    12 │ KARPAL SINGH A/L RAM SINGH         │       1941 │ male    │ other      │ DAP       │ Pulau Pinang │ Bukit Gelugor    │ P051        │ NULL       │ NULL                        │ 2008-03-08 │ 2013-04-03 │
│       848 │    13 │ KARPAL SINGH A/L RAM SINGH         │       1941 │ male    │ other      │ DAP       │ Pulau Pinang │ Bukit Gelugor    │ P051        │ NULL       │ NULL                        │ 2013-05-05 │ 2014-04-17 │
│       872 │    12 │ TENGKU RAZALEIGH BIN TENGKU HAMZAH │       1937 │ male    │ bumiputera │ BN - UMNO │ Kelantan     │ Gua Musang       │ P032        │ NULL       │ NULL                        │ 2008-03-08 │ 2013-04-03 │
│       872 │    13 │ TENGKU RAZALEIGH BIN TENGKU HAMZAH │       1937 │ male    │ bumiputera │ BN - UMNO │ Kelantan     │ Gua Musang       │ P032        │ NULL       │ NULL                        │ 2013-05-05 │ 2018-04-07 │
│        ·  │     · │       ·                            │         ·  │  ·      │     ·      │  ·        │  ·           │  ·               │  ·          │  ·         │  ·                          │     ·      │     ·      │
│        ·  │     · │       ·                            │         ·  │  ·      │     ·      │  ·        │  ·           │  ·               │  ·          │  ·         │  ·                          │     ·      │     ·      │
│        ·  │     · │       ·                            │         ·  │  ·      │     ·      │  ·        │  ·           │  ·               │  ·          │  ·         │  ·                          │     ·      │     ·      │
│   9999992 │    13 │ ROOSME HAMZAH                      │       NULL │ female  │ bumiputera │ NULL      │ NULL         │ NULL             │ NULL        │ NULL       │ Setiausaha Dewan Rakyat     │ 2013-05-05 │ 2018-04-07 │
│   9999993 │    14 │ NIZAM MYDIN BIN BACHA MYDIN        │       1975 │ male    │ bumiputera │ NULL      │ NULL         │ NULL             │ NULL        │ NULL       │ Setiausaha Dewan Rakyat     │ 2018-05-09 │ 2022-10-10 │
│   9999993 │    15 │ NIZAM MYDIN BIN BACHA MYDIN        │       1975 │ male    │ bumiputera │ NULL      │ NULL         │ NULL             │ NULL        │ NULL       │ Setiausaha Dewan Rakyat     │ 2022-11-19 │ NULL       │
│   9999995 │    14 │ AZHAR AZIZAN HARUN                 │       1962 │ male    │ bumiputera │ NULL      │ NULL         │ NULL             │ NULL        │ NULL       │ Yang di-Pertua Dewan Rakyat │ 2018-05-09 │ 2022-10-10 │
│  10000000 │    12 │ MOHD ABDUL WAHID BIN HAJI ENDUT    │       1950 │ male    │ bumiputera │ PAS       │ Terengganu   │ Kuala Terengganu │ P036        │ NULL       │ NULL                        │ 2009-01-17 │ 2013-04-03 │
│  10000001 │    15 │ AZAHAR BIN HASAN                   │       1970 │ male    │ bumiputera │ BERSATU   │ Perlis       │ NULL             │ NULL        │ NULL       │ Ahli Dewan Negara           │ 2024-09-10 │ 2027-09-09 │
│  10000002 │    13 │ AZMAN BIN ISMAIL                   │       1961 │ male    │ bumiputera │ PKR       │ Kedah        │ Kuala Kedah      │ P010        │ NULL       │ NULL                        │ 2013-05-05 │ 2018-04-07 │
│  10000002 │    14 │ AZMAN BIN ISMAIL                   │       1961 │ male    │ bumiputera │ PH - PKR  │ Kedah        │ KUALA KEDAH      │ P010        │ NULL       │ NULL                        │ 2018-05-09 │ 2022-10-10 │
│  10000003 │    13 │ RIDUAN BIN RAHMAT                  │       NULL │ male    │ bumiputera │ NULL      │ NULL         │ NULL             │ NULL        │ NULL       │ Setiausaha Dewan Negara     │ NULL       │ NULL       │
│  10000004 │    13 │ MOHD SUHAIMI BIN ABDULLAH          │       1980 │ male    │ bumiputera │ BN - UMNO │ Kedah        │ NULL             │ NULL        │ NULL       │ NULL                        │ 2014-05-21 │ 2017-05-20 │
├───────────┴───────┴────────────────────────────────────┴────────────┴─────────┴────────────┴───────────┴──────────────┴──────────────────┴─────────────┴────────────┴─────────────────────────────┴────────────┴────────────┤
│ 1236 rows (20 shown)                                                                                                                                                                                             14 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [33]:
duckdb.sql("select author, count(*) as count FROM (SELECT DISTINCT author_id, author, birth_year, sex, ethnicity FROM df) GROUP BY author ORDER BY COUNT DESC")

┌───────────────────────────────────────┬───────┐
│                author                 │ count │
│                varchar                │ int64 │
├───────────────────────────────────────┼───────┤
│ JOHARI BIN ABDUL GHANI                │     1 │
│ WAN AHMAD FAYHSAL BIN WAN AHMAD KAMAL │     1 │
│ GOOI HSIAO-LEUNG                      │     1 │
│ WONG TIEN FATT @ WONG NYUK FOH        │     1 │
│ LIHAN JOK                             │     1 │
│ ABDUL NASIR BIN HAJI IDRIS            │     1 │
│ JAMILAH @ HALIMAH BINTI SULAIMAN      │     1 │
│ MUSTAFA BIN MUSA                      │     1 │
│ YAHAYA BIN MAT GHANI @ ABBAS          │     1 │
│ AHMAD BIN KASIM                       │     1 │
│       ·                               │     · │
│       ·                               │     · │
│       ·                               │     · │
│ GWO-BURNE LOH                         │     1 │
│ ZAKARIA BIN MOHD. EDRIS               │     1 │
│ IZANI BIN HUSIN                       │     1 │
│ SHAZIMAN BIN ABU MANSOR               │     1 │
│ MUSLIMIN BIN YAHAYA                   │     1 │
│ JULIAN TAN KOK PING                   │     1 │
│ AZMAN BIN NASRUDIN                    │     1 │
│ ABD GHANI BIN AHMAD                   │     1 │
│ LAJIM BIN HAJI UKIN                   │     1 │
│ OTHMAN BIN ABDUL                      │     1 │
├───────────────────────────────────────┴───────┤
│ 701 rows (20 shown)                 2 columns │
└───────────────────────────────────────────────┘

In [34]:
import pandas as pd

In [44]:
pd.read_parquet("author_history_2025_03_21.parquet").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1236 entries, 0 to 1235
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   author_id      1236 non-null   int64
 1   vol            1236 non-null   int64
 2   author         1236 non-null   object
 3   birth_year     1053 non-null   float64
 4   sex            1236 non-null   object
 5   ethnicity      1236 non-null   object
 6   party          1226 non-null   object
 7   negeri         1101 non-null   object
 8   area           1020 non-null   object
 9   kod_kawasan    1020 non-null   object
 10  exec_posts     286 non-null    object
 11  service_posts  143 non-null    object
 12  start_date     1234 non-null   object
 13  end_date       1008 non-null   object
dtypes: float64(1), int64(2), object(11)
memory usage: 135.3+ KB

In [ ]:
df.start_date.dtype

AttributeError: This relation does not contain a column by the name of 'dtype'

In [50]:
import pandas as pd
df_full = pd.read_csv("author_history_with_term_2025-03-21.csv")
df_full["start_date"] = pd.to_datetime(df_full["start_date"])
df_full["end_date"] = pd.to_datetime(df_full["end_date"])
df_full

,author_id,vol,author,birth_year,sex,ethnicity,party,negeri,area,kod_kawasan,exec_posts,service_posts,start_date,end_date
0,375,14,MAHATHIR BIN MOHAMAD,1926.0,male,bumiputera,BERSATU,Kedah,LANGKAWI,P004,NaN,NaN,2018-05-09,2020-05-28
1,375,14,MAHATHIR BIN MOHAMAD,1926.0,male,bumiputera,BEBAS,Kedah,LANGKAWI,P004,NaN,NaN,2020-05-28,2020-08-12
2,375,14,MAHATHIR BIN MOHAMAD,1926.0,male,bumiputera,PEJUANG,Kedah,LANGKAWI,P004,NaN,NaN,2020-08-12,2022-10-10
3,698,12,LIM KIT SIANG,1941.0,male,chinese,DAP,Perak,Ipoh Timur,P064,NaN,NaN,2008-03-08,2013-04-03
4,698,13,LIM KIT SIANG,1941.0,male,chinese,DAP,Johor,Gelang Patah,P162,NaN,NaN,2013-05-05,2018-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231,10000001,15,AZAHAR BIN HASAN,1970.0,male,bumiputera,BERSATU,Perlis,NaN,NaN,NaN,Ahli Dewan Negara,2024-09-10,2027-09-09
1232,10000002,13,AZMAN BIN ISMAIL,1961.0,male,bumiputera,PKR,Kedah,Kuala Kedah,P010,NaN,NaN,2013-05-05,2018-04-07
1233,10000002,14,AZMAN BIN ISMAIL,1961.0,male,bumiputera,PH - PKR,Kedah,KUALA KEDAH,P010,NaN,NaN,2018-05-09,2022-10-10
1234,10000003,13,RIDUAN BIN RAHMAT,NaN,male,bumiputera,NaN,NaN,NaN,NaN,NaN,Setiausaha Dewan Negara,NaT,NaT
1235,10000004,13,MOHD SUHAIMI BIN ABDULLAH,1980.0,male,bumiputera,BN - UMNO,Kedah,NaN,NaN,NaN,NaN,2014-05-21,2017-05-20

In [51]:
df_full.to_csv("author_history_2025_03_21.csv", index=False)
df_full.to_parquet("author_history_2025_03_21.parquet", index=False)

In [52]:
df_full[["author_id","author","birth_year","sex","ethnicity"]].drop_duplicates()["author_id"].value_counts().reset_index()[df_full[["author_id","author","birth_year","sex","ethnicity"]].drop_duplicates()["author_id"].value_counts().reset_index()["count"] > 1]["author_id"].values
df_author = df_full[["author_id","author","birth_year","sex","ethnicity"]].drop_duplicates()
# df_author = df_author.drop(769)
df_author = df_author.reset_index(drop=True)
df_author

,author_id,author,birth_year,sex,ethnicity
0,375,MAHATHIR BIN MOHAMAD,1926.0,male,bumiputera
1,698,LIM KIT SIANG,1941.0,male,chinese
2,848,KARPAL SINGH A/L RAM SINGH,1941.0,male,other
3,872,TENGKU RAZALEIGH BIN TENGKU HAMZAH,1937.0,male,bumiputera
4,985,S. SUBRAMANIAM,1953.0,male,indian
...,...,...,...,...,...
696,10000000,MOHD ABDUL WAHID BIN HAJI ENDUT,1950.0,male,bumiputera
697,10000001,AZAHAR BIN HASAN,1970.0,male,bumiputera
698,10000002,AZMAN BIN ISMAIL,1961.0,male,bumiputera
699,10000003,RIDUAN BIN RAHMAT,NaN,male,bumiputera
700,10000004,MOHD SUHAIMI BIN ABDULLAH,1980.0,male,bumiputera

In [53]:
df_author.to_csv("author_2025_03_21.csv", index=False)
df_author.to_parquet("author_2025_03_21.parquet", index=False)